#############################################################################
# Makefile for building: bin/SwarmVis
# Generated by qmake (2.01a) (Qt 4.4.0) on: Tue Nov 18 08:04:22 2008
# Project:  swarmvis.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile swarmvis.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtOpenGL -I/usr/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib64 -L/usr/X11R6/lib64 -lQtOpenGL -L/usr/lib64 -L/usr/X11R6/lib64 -lQtGui -lpng -lSM -lICE -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lrt -ldl -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Agent/AgentArray.cpp \
		src/Agent/Agent.cpp \
		src/OpenGL/glwidget.cpp \
		src/Thread/mythread.cpp \
		src/main.cpp \
		src/swarmvis.cpp moc_glwidget.cpp \
		moc_mythread.cpp \
		moc_swarmvis.cpp
OBJECTS       = AgentArray.o \
		Agent.o \
		glwidget.o \
		mythread.o \
		main.o \
		swarmvis.o \
		moc_glwidget.o \
		moc_mythread.o \
		moc_swarmvis.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		swarmvis.pro
QMAKE_TARGET  = SwarmVis
DESTDIR       = bin/
TARGET        = bin/SwarmVis

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_swarmvis.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: swarmvis.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib64/libQtOpenGL.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -unix -o Makefile swarmvis.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib64/libQtOpenGL.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile swarmvis.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SwarmVis1.0.0 || $(MKDIR) .tmp/SwarmVis1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SwarmVis1.0.0/ && $(COPY_FILE) --parents src/Agent/Agent.h src/Agent/AgentArray.h src/OpenGL/glwidget.h src/Thread/mythread.h src/swarmvis.h .tmp/SwarmVis1.0.0/ && $(COPY_FILE) --parents src/Agent/AgentArray.cpp src/Agent/Agent.cpp src/OpenGL/glwidget.cpp src/Thread/mythread.cpp src/main.cpp src/swarmvis.cpp .tmp/SwarmVis1.0.0/ && $(COPY_FILE) --parents src/swarmvis.ui .tmp/SwarmVis1.0.0/ && (cd `dirname .tmp/SwarmVis1.0.0` && $(TAR) SwarmVis1.0.0.tar SwarmVis1.0.0 && $(COMPRESS) SwarmVis1.0.0.tar) && $(MOVE) `dirname .tmp/SwarmVis1.0.0`/SwarmVis1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SwarmVis1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_glwidget.cpp moc_mythread.cpp moc_swarmvis.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_mythread.cpp moc_swarmvis.cpp
moc_glwidget.cpp: src/Agent/AgentArray.h \
		src/Agent/Agent.h \
		src/OpenGL/glwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/OpenGL/glwidget.h -o moc_glwidget.cpp

moc_mythread.cpp: src/Thread/mythread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/Thread/mythread.h -o moc_mythread.cpp

moc_swarmvis.cpp: ui_swarmvis.h \
		src/Thread/mythread.h \
		src/OpenGL/glwidget.h \
		src/Agent/AgentArray.h \
		src/Agent/Agent.h \
		src/swarmvis.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/swarmvis.h -o moc_swarmvis.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_swarmvis.h
compiler_uic_clean:
	-$(DEL_FILE) ui_swarmvis.h
ui_swarmvis.h: src/swarmvis.ui
	/usr/bin/uic src/swarmvis.ui -o ui_swarmvis.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

AgentArray.o: src/Agent/AgentArray.cpp src/Agent/AgentArray.h \
		src/Agent/Agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AgentArray.o src/Agent/AgentArray.cpp

Agent.o: src/Agent/Agent.cpp src/Agent/Agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Agent.o src/Agent/Agent.cpp

glwidget.o: src/OpenGL/glwidget.cpp src/OpenGL/glwidget.h \
		src/Agent/AgentArray.h \
		src/Agent/Agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o src/OpenGL/glwidget.cpp

mythread.o: src/Thread/mythread.cpp src/Thread/mythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mythread.o src/Thread/mythread.cpp

main.o: src/main.cpp src/swarmvis.h \
		ui_swarmvis.h \
		src/Thread/mythread.h \
		src/OpenGL/glwidget.h \
		src/Agent/AgentArray.h \
		src/Agent/Agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

swarmvis.o: src/swarmvis.cpp src/swarmvis.h \
		ui_swarmvis.h \
		src/Thread/mythread.h \
		src/OpenGL/glwidget.h \
		src/Agent/AgentArray.h \
		src/Agent/Agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swarmvis.o src/swarmvis.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_mythread.o: moc_mythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mythread.o moc_mythread.cpp

moc_swarmvis.o: moc_swarmvis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_swarmvis.o moc_swarmvis.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

